### ISSUE TITLE
Mousing over Follow buttons reorders the list

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/fritter#12]
### weird bug

trying to follow people, mousing over different Follow buttons in the list, each one seems to re-order the list (so the button i'm trying to click on jumps out from under the mouse)

![bug](https://user-images.githubusercontent.com/169280/34842811-73585dda-f6c1-11e7-8026-89f8b345030d.gif)

cc @taravancil

**Comment by dcposch** [comment]
update: i can't reproduce it now... maybe it happens only on startup when dats are still loading?

*Beaker version:* 0.7.10
*Fritter version:* Revision 219

**Comment by taravancil** [comment]
I fixed it this morning, that's why you're no longer seeing it 😄
