### ISSUE TITLE
Move version info to the view

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/fritter#41]
Content should go in the view, not the sidebar

![screen shot 2018-07-04 at 10 33 43 am](https://user-images.githubusercontent.com/7584833/42285634-d83fd574-7f75-11e8-8c96-af24bd2e2fda.png)

**Comment by taravancil** [comment]
Yeah I asked @pfrazee to do that when he added the version info, he’ll get
around to it when we’re back from vacation

**Comment by DKunin** [comment]
I know it's not much,  but I still would like to help:
https://github.com/beakerbrowser/fritter/pull/44

Have a nice vacation!

**Comment by pfrazee** [comment]
Thanks!
